In [30]:
# import our dependencies
import pandas as pd
import gmaps
import requests 
# Import the API key.
from config2 import g_key

In [18]:
file_to_load = "weather_data/cities.csv"
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv(file_to_load)
city_data_df.head(10)

,City ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Mazagao,BR,2020-10-24 01:43:23,-0.12,-51.29,84.20,74,0,13.87
1,1,Jalu,LY,2020-10-24 01:43:23,29.03,21.55,63.07,83,0,10.49
2,2,Albany,US,2020-10-24 01:43:24,42.60,-73.97,64.99,84,15,7.83
3,3,Jamestown,US,2020-10-24 01:43:24,42.10,-79.24,70.00,60,75,12.75
4,4,Severo-Kurilsk,RU,2020-10-24 01:43:24,50.68,156.12,43.57,86,100,37.18
5,5,Punta Arenas,CL,2020-10-24 01:43:24,-53.15,-70.92,44.60,65,75,5.82
6,6,Avdiyivka,UA,2020-10-24 01:43:25,48.14,37.74,54.34,96,100,8.66
7,7,College,US,2020-10-24 01:43:25,64.86,-147.80,28.00,79,75,2.48
8,8,Burnie,AU,2020-10-24 01:38:28,-41.07,145.92,57.88,51,89,11.81
9,9,Longkou,CN,2020-10-24 01:43:25,37.65,120.33,57.25,49,0,15.30

In [19]:
city_data_df.dtypes

City ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [20]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [21]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
max_temp = city_data_df["Max Temp"]
new_max_temp = [max(temp,0) for temp in max_temp]
# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure()
# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(locations, weights=new_max_temp)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
max_temp = city_data_df["Max Temp"]
new_max_temp = [max(temp,0) for temp in max_temp]
# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(locations, weights=new_max_temp, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
# Heatmap of Cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
# Heatmap of Wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [26]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 89

In [27]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)].dropna()
preferred_cities_df

,City ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Mazagao,BR,2020-10-24 01:43:23,-0.12,-51.29,84.20,74,0,13.87
10,10,Avarua,CK,2020-10-24 01:43:25,-21.21,-159.78,77.00,69,59,16.11
20,20,Georgetown,MY,2020-10-24 01:38:55,5.41,100.34,82.40,83,20,3.96
22,22,Adrar,MR,2020-10-24 01:43:28,20.50,-10.07,85.51,15,64,6.87
26,26,Vaini,TO,2020-10-24 01:43:29,-21.20,-175.20,78.80,74,40,13.87
...,...,...,...,...,...,...,...,...,...,...
557,557,Ambon,ID,2020-10-24 01:45:31,-3.70,128.18,87.80,70,40,3.36
559,559,Kloulklubed,PW,2020-10-24 01:45:32,7.04,134.26,86.00,74,75,6.93
560,560,Akyab,MM,2020-10-24 01:45:32,20.15,92.90,81.59,85,100,13.78
561,561,Buchanan,LR,2020-10-24 01:45:32,5.88,-10.05,77.14,88,95,6.64
564,564,Haifa,IL,2020-10-24 01:45:33,32.82,34.99,77.00,26,20,3.00

In [28]:
preferred_cities_df.count()

City ID       151
City          151
Country       151
Date          151
Lat           151
Lng           151
Max Temp      151
Humidity      151
Cloudiness    151
Wind Speed    151
dtype: int64

In [29]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

          City Country  Max Temp    Lat     Lng Hotel Name
0      Mazagao      BR     84.20  -0.12  -51.29
10      Avarua      CK     77.00 -21.21 -159.78
20  Georgetown      MY     82.40   5.41  100.34
22       Adrar      MR     85.51  20.50  -10.07
26       Vaini      TO     78.80 -21.20 -175.20
28  Butaritari      KI     81.93   3.07  172.79
29       Kapaa      US     82.00  22.08 -159.32
30  Sao Filipe      CV     79.95  14.90  -24.50
33  San Andres      CO     80.60  12.58  -81.70
35        Poum      NC     78.37 -20.23  164.02

In [31]:
# Set parameters to search for a hotel.
parameters = { "radius": 5000,
               "type" : "lodging",
               "key"  : g_key
    
}

In [43]:
# Iterate through the DataFrame.
for index,row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"] 
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    parameters["location"] = f"{lat},{lng}"
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=parameters).json()
    try:
        # Grab the first hotel from the results and store the name.
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except IndexError:
        print("Hotel name not found, Skipping")

Hotel name not found, Skipping
Hotel name not found, Skipping
Hotel name not found, Skipping
Hotel name not found, Skipping
Hotel name not found, Skipping
Hotel name not found, Skipping
Hotel name not found, Skipping
Hotel name not found, Skipping
Hotel name not found, Skipping
Hotel name not found, Skipping
Hotel name not found, Skipping

In [44]:
hotel_df

            City Country  Max Temp    Lat     Lng                Hotel Name
0        Mazagao      BR     84.20  -0.12  -51.29          Casa Lima Santos
10        Avarua      CK     77.00 -21.21 -159.78              Paradise Inn
20    Georgetown      MY     82.40   5.41  100.34            Cititel Penang
22         Adrar      MR     85.51  20.50  -10.07
26         Vaini      TO     78.80 -21.20 -175.20       Keleti Beach Resort
..           ...     ...       ...    ...     ...                       ...
557        Ambon      ID     87.80  -3.70  128.18      Swiss-Belhotel Ambon
559  Kloulklubed      PW     86.00   7.04  134.26   Storyboard Beach Resort
560        Akyab      MM     81.59  20.15   92.90              Hotel Memory
561     Buchanan      LR     77.14   5.88  -10.05       Kamaneahn Hotel Inc
564        Haifa      IL     77.00  32.82   34.99  Dan Panorama Haifa Hotel

[151 rows x 6 columns]

In [45]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [46]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [47]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [49]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
hotel_info

['\n<dl>\n<dt>Hotel Name</dt><dd>Casa Lima Santos</dd>\n<dt>City</dt><dd>Mazagao</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>84.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Paradise Inn</dd>\n<dt>City</dt><dd>Avarua</dd>\n<dt>Country</dt><dd>CK</dd>\n<dt>Max Temp</dt><dd>77.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Cititel Penang</dd>\n<dt>City</dt><dd>Georgetown</dd>\n<dt>Country</dt><dd>MY</dd>\n<dt>Max Temp</dt><dd>82.4 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Adrar</dd>\n<dt>Country</dt><dd>MR</dd>\n<dt>Max Temp</dt><dd>85.51 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Keleti Beach Resort</dd>\n<dt>City</dt><dd>Vaini</dd>\n<dt>Country</dt><dd>TO</dd>\n<dt>Max Temp</dt><dd>78.8 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Isles Sunset Lodge</dd>\n<dt>City</dt><dd>Butaritari</dd>\n<dt>Country</dt><dd>KI</dd>\n<dt>Max Temp</dt><dd>81.93 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sheraton Kauai Resort at Coconut Beach</dd>\n<dt>City</dt><dd>Kapaa</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>82.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Tortuga B&B</dd>\n<dt>City</dt><dd>Sao Filipe</dd>\n<dt>Country</dt><dd>CV</dd>\n<dt>Max Temp</dt><dd>79.95 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Arena Blanca</dd>\n<dt>City</dt><dd>San Andres</dd>\n<dt>Country</dt><dd>CO</dd>\n<dt>Max Temp</dt><dd>80.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Gîte kajeon</dd>\n<dt>City</dt><dd>Poum</dd>\n<dt>Country</dt><dd>NC</dd>\n<dt>Max Temp</dt><dd>78.37 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Villa Enata</dd>\n<dt>City</dt><dd>Atuona</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Max Temp</dt><dd>78.84 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Heritage Park Hotel</dd>\n<dt>City</dt><dd>Honiara</dd>\n<dt>Country</dt><dd>SB</dd>\n<dt>Max Temp</dt><dd>87.8 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Camp Pasica</dd>\n<dt>City</dt><dd>Dingle</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>77.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Oumou Elghoura</dd>\n<dt>City</dt><dd>Atar</dd>\n<dt>Country</dt><dd>MR</dd>\n<dt>Max Temp</dt><dd>83.88 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Tesoro Los Cabos</dd>\n<dt>City</dt><dd>Cabo San Lucas</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Max Temp</dt><dd>86.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Amaloh Boutique Resort</dd>\n<dt>City</dt><dd>Matara</dd>\n<dt>Country</dt><dd>LK</dd>\n<dt>Max Temp</dt><dd>80.4 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>ibis Styles Mt Isa Verona</dd>\n<dt>City</dt><dd>Mount Isa</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Max Temp</dt><dd>84.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Osprey Beach Hotel</dd>\n<dt>City</dt><dd>Cockburn Town</dd>\n<dt>Country</dt><dd>TC</dd>\n<dt>Max Temp</dt><dd>83.05 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotels in Lakshadweep Islands</dd>\n<dt>City</dt><dd>Kavaratti</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>80.47 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Grand Dafam Bela Ternate</dd>\n<dt>City</dt><dd>Ternate</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>84.51 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>ProDAF/Diffa</dd>\n<dt>City</dt><dd>Diffa</dd>\n<dt>Country</dt><dd>NE</dd>\n<dt>Max Temp</dt><dd>80.15 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Scoop Guest House</dd>\n<dt>City</dt><dd>Hithadhoo</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Max Temp</dt><dd>82.85 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Maringe Lagoon Lodge</dd>\n<dt>City</dt><dd>Buala</dd>\n<dt>Country</dt><dd>SB</dd>\n<dt>Max Temp</dt><dd>86.77 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hilo Hawaiian Hotel</dd>\n<dt>City</dt><dd>Hilo</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>87.8 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>OYO 412 Viewfort Venue</dd>\n<dt>City</dt><dd>San Pedro</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>84.99 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Crôa Mares Hotel</dd>\n<dt>City</dt><dd>Sao Jose Da Coroa Grande</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>76.3 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Prata</dd>\n<dt>City</dt><dd>Vitoria</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>77.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Meligai Kapit</dd>\n<dt>City</dt><dd>Kapit</dd>\n<dt>Country</dt><dd>MY</dd>\n<dt>Max Temp</dt><dd>78.03 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Las Casitas Santa Rosalia</dd>\n<dt>City</dt><dd>Santa Rosalia</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Max Temp</dt><dd>77.63 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Fengshui Residence</dd>\n<dt>City</dt><dd>Port-Gentil</dd>\n<dt>Country</dt><dd>GA</dd>\n<dt>Max Temp</dt><dd>78.1 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Dhidhoo beach</dd>\n<dt>City</dt><dd>Dhidhdhoo</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Max Temp</dt><dd>81.97 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Executivo Palace</dd>\n<dt>City</dt><dd>Sao Miguel Do Araguaia</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>75.09 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Moon light Furnished Units</dd>\n<dt>City</dt><dd>Umm Lajj</dd>\n<dt>Country</dt><dd>SA</dd>\n<dt>Max Temp</dt><dd>82.98 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Bungalow 63</dd>\n<dt>City</dt><dd>Hambantota</dd>\n<dt>Country</dt><dd>LK</dd>\n<dt>Max Temp</dt><dd>75.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Stadium Hotel</dd>\n<dt>City</dt><dd>Miramar</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>81.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Vegas Hotel And Lodging.</dd>\n<dt>City</dt><dd>Manor</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>77.07 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Trump International Hotel & Tower Panama</dd>\n<dt>City</dt><dd>Panama City</dd>\n<dt>Country</dt><dd>PA</dd>\n<dt>Max Temp</dt><dd>78.8 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Pousada 100 Passos</dd>\n<dt>City</dt><dd>Tamandare</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>76.35 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Valley Breeze Guest House</dd>\n<dt>City</dt><dd>Grenville</dd>\n<dt>Country</dt><dd>GD</dd>\n<dt>Max Temp</dt><dd>78.8 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Gouranga Hindu Hotel</dd>\n<dt>City</dt><dd>Kenda</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>75.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sundowners Vacation Villas</dd>\n<dt>City</dt><dd>Binabalian</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>82.47 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Amrut Bagh Resort</dd>\n<dt>City</dt><dd>Bhachau</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>78.08 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Aitape</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>85.42 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Thinadhoo</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Max Temp</dt><dd>83.62 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Motel 6 Sinton, TX</dd>\n<dt>City</dt><dd>San Patricio</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>80.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>In Wewak Boutique Hotel</dd>\n<dt>City</dt><dd>Wewak</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>85.12 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>ڳوٺ چوڌري جلال الدين جٽ</dd>\n<dt>City</dt><dd>Kadhan</dd>\n<dt>Country</dt><dd>PK</dd>\n<dt>Max Temp</dt><dd>75.29 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Mercure Maceio Pajucara Hotel</dd>\n<dt>City</dt><dd>Maceio</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>75.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>akwa reef lodge</dd>\n<dt>City</dt><dd>Ailigandi</dd>\n<dt>Country</dt><dd>PA</dd>\n<dt>Max Temp</dt><dd>80.4 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Juba</dd>\n<dt>City</dt><dd>Mogadishu</dd>\n<dt>Country</dt><dd>SO</dd>\n<dt>Max Temp</dt><dd>79.95 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>SPOT ON 49653 Rajasthan Guest House SPOT</dd>\n<dt>City</dt><dd>Chakradharpur</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>75.2 °F</dd>\n</dl>\n',
 "\n<dl>\n<dt>Hotel Name</dt><dd>Maia's Beach Resort</dd>\n<dt>City</dt><dd>Sulangan</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>82.15 °F</dd>\n</dl>\n",
 "\n<dl>\n<dt>Hotel Name</dt><dd>Marriott's Ko Olina Beach Club</dd>\n<dt>City</dt><dd>Makakilo City</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>82.4 °F</dd>\n</dl>\n",
 '\n<dl>\n<dt>Hotel Name</dt><dd>Khách Sạn Mường Thanh Luxury Cà Mau</dd>\n<dt>City</dt><dd>Ca Mau</dd>\n<dt>Country</dt><dd>VN</dd>\n<dt>Max Temp</dt><dd>79.32 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel FX72 Ruteng</dd>\n<dt>City</dt><dd>Ruteng</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>77.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Nusantara Nabire</dd>\n<dt>City</dt><dd>Nabire</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>79.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Pyramid Hotel</dd>\n<dt>City</dt><dd>Sisophon</dd>\n<dt>Country</dt><dd>KH</dd>\n<dt>Max Temp</dt><dd>75.78 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Nusa Island Retreat</dd>\n<dt>City</dt><dd>Kavieng</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>85.32 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Grage Hotel Bengkulu</dd>\n<dt>City</dt><dd>Bengkulu</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>78.62 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>HS Hotsson Smart Acapulco</dd>\n<dt>City</dt><dd>Acapulco</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Max Temp</dt><dd>84.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Juvinal Martin</dd>\n<dt>City</dt><dd>Airai</dd>\n<dt>Country</dt><dd>TL</dd>\n<dt>Max Temp</dt><dd>79.07 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Bora-Bora Pearl Beach Resort & Spa</dd>\n<dt>City</dt><dd>Faanui</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Max Temp</dt><dd>79.25 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Lorengau Harbourside Hotel</dd>\n<dt>City</dt><dd>Lorengau</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>85.87 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hospitality Carnarvon</dd>\n<dt>City</dt><dd>Carnarvon</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Max Temp</dt><dd>77.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Rainha do Vale</dd>\n<dt>City</dt><dd>Itaporanga</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>77.38 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Beuleup counda motel</dd>\n<dt>City</dt><dd>Kaffrine</dd>\n<dt>Country</dt><dd>SN</dd>\n<dt>Max Temp</dt><dd>80.22 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Aipana Plaza Hotel</dd>\n<dt>City</dt><dd>Boa Vista</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>78.8 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>The Esplanade Hotel</dd>\n<dt>City</dt><dd>Port Hedland</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Max Temp</dt><dd>84.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sur Plaza Hotel</dd>\n<dt>City</dt><dd>Sur</dd>\n<dt>Country</dt><dd>OM</dd>\n<dt>Max Temp</dt><dd>77.94 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Derogongan Residence</dd>\n<dt>City</dt><dd>Marawi</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>82.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Moondarra Motel</dd>\n<dt>City</dt><dd>Innisfail</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Max Temp</dt><dd>83.28 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Okra Leaf Guest House Syariah</dd>\n<dt>City</dt><dd>Bontang</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>82.83 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Santa Mônica</dd>\n<dt>City</dt><dd>Mozarlandia</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>78.73 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>VS Villa</dd>\n<dt>City</dt><dd>Kalmunai</dd>\n<dt>Country</dt><dd>LK</dd>\n<dt>Max Temp</dt><dd>82.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Atlantis Hotel</dd>\n<dt>City</dt><dd>Bathsheba</dd>\n<dt>Country</dt><dd>BB</dd>\n<dt>Max Temp</dt><dd>84.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>The Sebel Kiama Harbourside</dd>\n<dt>City</dt><dd>Kiama</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Max Temp</dt><dd>79.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>INN NEW HORIZON</dd>\n<dt>City</dt><dd>Touros</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>77.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Taloa Heights</dd>\n<dt>City</dt><dd>Alofi</dd>\n<dt>Country</dt><dd>NU</dd>\n<dt>Max Temp</dt><dd>80.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Kudahuvadhoo Retreat</dd>\n<dt>City</dt><dd>Kudahuvadhoo</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Max Temp</dt><dd>82.31 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Urban Style by Front One</dd>\n<dt>City</dt><dd>Pringsewu</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>85.03 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>POUSADA O RECANTO</dd>\n<dt>City</dt><dd>Pombas</dd>\n<dt>Country</dt><dd>CV</dd>\n<dt>Max Temp</dt><dd>78.8 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>ibis Styles Karratha</dd>\n<dt>City</dt><dd>Karratha</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Max Temp</dt><dd>82.67 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Foyer ADM</dd>\n<dt>City</dt><dd>Mitsamiouli</dd>\n<dt>Country</dt><dd>KM</dd>\n<dt>Max Temp</dt><dd>78.87 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Dubti</dd>\n<dt>Country</dt><dd>ET</dd>\n<dt>Max Temp</dt><dd>83.48 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Kimpton EPIC Hotel</dd>\n<dt>City</dt><dd>Miami</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>81.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>bador sepret</dd>\n<dt>City</dt><dd>Labuhan</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>86.34 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Amerik HOTEL</dd>\n<dt>City</dt><dd>Salina Cruz</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Max Temp</dt><dd>80.87 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Pin Drop Hotel</dd>\n<dt>City</dt><dd>Anloga</dd>\n<dt>Country</dt><dd>GH</dd>\n<dt>Max Temp</dt><dd>78.8 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Holiday Inn Selma-Swancourt</dd>\n<dt>City</dt><dd>Selma</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>77.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Tessalit</dd>\n<dt>Country</dt><dd>ML</dd>\n<dt>Max Temp</dt><dd>81.07 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Residence Inn by Marriott Gulfport-Biloxi Airport</dd>\n<dt>City</dt><dd>Harrison</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>78.8 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>LIKWALE LODGE</dd>\n<dt>City</dt><dd>Mayumba</dd>\n<dt>Country</dt><dd>GA</dd>\n<dt>Max Temp</dt><dd>76.51 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Volcano Sea View Tree House</dd>\n<dt>City</dt><dd>Isangel</dd>\n<dt>Country</dt><dd>VU</dd>\n<dt>Max Temp</dt><dd>80.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hôtel Le Dronmi</dd>\n<dt>City</dt><dd>Cayenne</dd>\n<dt>Country</dt><dd>GF</dd>\n<dt>Max Temp</dt><dd>77.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Mirage</dd>\n<dt>City</dt><dd>Vilhena</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>75.72 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Econo Lodge Kingsville</dd>\n<dt>City</dt><dd>Kingsville</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>80.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Rasma Bed and Breakfast</dd>\n<dt>City</dt><dd>Bobo Dioulasso</dd>\n<dt>Country</dt><dd>BF</dd>\n<dt>Max Temp</dt><dd>80.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Caribe</dd>\n<dt>City</dt><dd>Barahona</dd>\n<dt>Country</dt><dd>DO</dd>\n<dt>Max Temp</dt><dd>79.54 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>castelo pizzaria</dd>\n<dt>City</dt><dd>Acarau</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>79.07 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Puri Brata</dd>\n<dt>City</dt><dd>Bambanglipuro</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>84.94 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel The Royal Honours</dd>\n<dt>City</dt><dd>Mangrol</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>80.33 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sharif Plaza Hotel</dd>\n<dt>City</dt><dd>Garissa</dd>\n<dt>Country</dt><dd>KE</dd>\n<dt>Max Temp</dt><dd>77.16 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Rodeway Inn & Suites</dd>\n<dt>City</dt><dd>Blythe</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>84.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>The Gem Hotel Beaufort</dd>\n<dt>City</dt><dd>Beaufort</dd>\n<dt>Country</dt><dd>MY</dd>\n<dt>Max Temp</dt><dd>80.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Shelly Bay Resort</dd>\n<dt>City</dt><dd>Hervey Bay</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Max Temp</dt><dd>82.99 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Kieta</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>83.89 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Amassi Hotel Gash</dd>\n<dt>City</dt><dd>Kassala</dd>\n<dt>Country</dt><dd>SD</dd>\n<dt>Max Temp</dt><dd>82.11 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Minshuku Agaihama</dd>\n<dt>City</dt><dd>Nishihara</dd>\n<dt>Country</dt><dd>JP</dd>\n<dt>Max Temp</dt><dd>75.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Erlyn’s Sta Rosa City Home</dd>\n<dt>City</dt><dd>Santa Rosa</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>84.99 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Tombouctou</dd>\n<dt>Country</dt><dd>ML</dd>\n<dt>Max Temp</dt><dd>87.03 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Mpampa</dd>\n<dt>City</dt><dd>Soyo</dd>\n<dt>Country</dt><dd>AO</dd>\n<dt>Max Temp</dt><dd>76.64 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Mercure Padang</dd>\n<dt>City</dt><dd>Padang</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>83.71 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Windvillage</dd>\n<dt>City</dt><dd>Itarema</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>79.3 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Paradise Bay Resort</dd>\n<dt>City</dt><dd>Ahuimanu</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>80.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Le Monitel</dd>\n<dt>City</dt><dd>Koumac</dd>\n<dt>Country</dt><dd>NC</dd>\n<dt>Max Temp</dt><dd>81.48 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Montana Hotel Syariah</dd>\n<dt>City</dt><dd>Martapura</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>82.4 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Bonfim</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>81.21 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>JB Hotel</dd>\n<dt>City</dt><dd>Petrolina</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>77.45 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Kost Pria</dd>\n<dt>City</dt><dd>Meulaboh</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>82.81 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hôtel Raiatea Lodge</dd>\n<dt>City</dt><dd>Tevaitoa</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Max Temp</dt><dd>79.99 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>ZINGARA 76ft Catamaran, full crew-all included</dd>\n<dt>City</dt><dd>Road Town</dd>\n<dt>Country</dt><dd>VG</dd>\n<dt>Max Temp</dt><dd>84.0 °F</dd>\n</dl>\n',

In [51]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))